package token;
//Tipos de token que vamos a usar
public enum TiposToken {
	T_MENOS, T_BOOLEAN, T_FUNC, T_INT, T_ID, T_ENTERO, T_CADENA,T_IGUAL,
	T_NEGAR, T_DISTINTO, T_POSTDECREMENTO, T_PRINT, T_INPUT, T_RETURN, T_STRING,
	T_VAR, T_SWITCH, T_CASE, T_DEFAULT, T_BREAK, T_TRUE, T_FALSE, T_LLAVEABRE, T_LLAVECIERRA,
	T_PUNTOCOMA, T_COMA, T_PARENTESISABRE, T_PARENTESISCIERRA, T_END;
	
}
