package token;
//Tipos de token que vamos a usar
public enum TiposToken {
	TMENOS, TBOOLEAN, TFUNC, TINT, TID, TENTERO, TCADENA,TIGUAL,
	TPOSTDECREMENTO, TPRINT, TINPUT, TRETURN, TSTRING,
	TVAR, TSWITCH, TCASE, TDEFAULT, TBREAK, TTRUE, TFALSE, TLLAVEABRE, TLLAVECIERRA,
	TPUNTOCOMA, TCOMA, TPARENTESISABRE, TVACIO, TPARENTESISCIERRA,TSUMA,TERROR, TDOSPUNTOS, TCOMENTABRE, TCOMENTCIERRA,
	TDISTINTO, EOL, EOF, TAND, TMENOR, TIF, TOK;
	
}
